version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
      - scripts/get-db-creds.sh
      - scripts/create-dockerrun.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push
artifacts:
  files:
    - 'Dockerrun.aws.json'
