version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: wydbackend:latest
    environment:
      NODE_ENV: production
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    image: wydclient:latest
    environment:
      NODE_ENV: production
  nginx:
    build: packages/nginx
    depends_on:
      - client
      - backend
    ports:
      - '80:80'
