version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: wydbackend:latest
    environment:
      NODE_ENV: production
    volumes:
      - ~/.aws:/root/.aws:ro
  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    image: wydclient:latest
    environment:
      NODE_ENV: production
  nginx:
    build: packages/nginx
    image: wydnginx:latest
    depends_on:
      - client
      - backend
    ports:
      - '80:80'
