version: '3'
services:
  wydbackend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/wydbackend:latest
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    volumes:
      - ~/.aws:/root/.aws:ro
  wydclient:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/wydclient:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
  wydnginx:
    build: packages/nginx
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/wydnginx:latest
    depends_on:
      - client
      - backend
    ports:
      - '80:80'
