import { Box, Button, Container, Grid, TextField, Typography } from '@mui/material';
import Image from "material-ui-image";
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from "react";
import styles from '../styles/Home.module.css'
import { Deal } from "./deal/deal";
import sampleDeals from "./deal/sampleDeals";
import PriceFormatter from "./util/PriceFormatter";

const Home: NextPage = () => {
  const [currentDeals, setCurrentDeals] = useState<Deal[], undefined>(sampleDeals);

  console.log(currentDeals);
  return (
    <div className={styles.container}>
      <Head>
        <title>What&apos;s Your Deal?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Box sx={{ m: 2 }} />
          <Button variant="contained">
            Get Notified
          </Button>
          <Box sx={{ m: 2 }} />

          <Typography variant="h3" component="div" gutterBottom>
            Find the nearest deals
          </Typography>

          <TextField fullWidth id="search" label="Search" variant="outlined" margin="normal" />
          <Box sx={{ m: 1 }} />

          <Typography variant="h8" component="div">
            TODO: Filter List here
          </Typography>
          <Box sx={{ m: 1 }} />

          <Typography align="left" variant="h4" component="div" gutterBottom>
            Nearby deals
          </Typography>

          <Grid container spacing={2}>
            {
              currentDeals.map(deal => {
                return (
                  <Grid item xs={6} key={deal.id}>
                    {
                      deal.image ? <Image src={deal.image} /> : <div></div>
                    }
                    <Typography variant="h6">{deal.storeName}</Typography>
                    <Typography variant="h7">{PriceFormatter.format(deal.currentPrice)}</Typography>
                  </Grid>
                );
              })
            }
          </Grid>
        </Container>

      </main>
    </div>
  )
}

export default Home
